### ISSUE TITLE
Create a unit test for the jupyter generate_io python script

### ISSUE THREAD

**Issue by dargasudarshan** [openebs/test-tools#23]
FEATURE REQUEST

What happened:

Thejupyter generate_io python script needs a unit-test to be created (Refer: https://github.com/openebs/test-tools/blob/master/jupyter-scripts/generate_io.py)

Anything else we need to know?:

References :
https://stackoverflow.com/questions/652292/what-is-unit-testing-and-how-do-you-do-it
http://pythontesting.net/framework/unittest/unittest-introduction/

**Comment by teisena** [comment]
Hey, could I take this up?

**Comment by dargasudarshan** [comment]
Sure @teisena  ! Thanks for signing up to work on this, looking forward to the PR! I am going ahead and adding issue-taken label.
