### ISSUE TITLE
Create a unit test for the jenkins load simulator python script

### ISSUE THREAD

**Issue by dargasudarshan** [openebs/test-tools#24]
FEATURE REQUEST

What happened:

The jenkins load simulator python script needs a unit-test to be created (Refer: https://github.com/openebs/test-tools/blob/master/jenkins-client/jenkins-load-simulator.py)

Anything else we need to know?:

References :
https://stackoverflow.com/questions/652292/what-is-unit-testing-and-how-do-you-do-it
http://pythontesting.net/framework/unittest/unittest-introduction/

**Comment by farhaanbukhsh** [comment]
Hey  this looks amazing to start, I would like to take this up.

**Comment by Shishuii** [comment]
Hi can I start working on it?

**Comment by andrewnester** [comment]
Hi everyone! I've seen no progress on this issue and went ahead and added unit PR cc @dargasudarshan 

https://github.com/openebs/test-tools/pull/36
