### ISSUE TITLE
Create the travis build pass badge on the test-tools README file 

### ISSUE THREAD

**Issue by ksatchit** [openebs/test-tools#26]
## Is this a BUG REPORT or FEATURE REQUEST?
FEATURE REQUEST

**What happened**:

- Add the badge for travis build status of this repo on the README file

**What you expected to happen**:

- Users can be appraised of the CI status of the various test tools (images) on the repo

**How to fix it**:

- https://shields.io/#/ can be used for this

**Comment by yamilurbina** [comment]
@ksatchit Hi! I went ahead and added the badge using shields.io: https://github.com/openebs/test-tools/pull/28

**Comment by 94151** [comment]
@ksatchit is this issue open?

**Comment by ksatchit** [comment]
Afraid not @94151 ! This is closed by #28
