### ISSUE TITLE
Improve the dockerfile for libiscsi image 

### ISSUE THREAD

**Issue by ksatchit** [openebs/test-tools#40]
## Is this a BUG REPORT or FEATURE REQUEST?
BUG REPORT 

**What happened**:

- Update the libiscsi dockerfile as per standard best practices: https://github.com/openebs/test-tools/tree/master/libiscsi

**What you expected to happen**:

- Optimized images

**References**:

- https://docs.docker.com/develop/develop-images/dockerfile_best-practices/

**Comment by clickyotomy** [comment]
Hello! Opened a PR for this https://github.com/openebs/test-tools/pull/48.
Apologies for the the duplicate PR (I forgot to sign-off my commit).

**Comment by valerianpereira** [comment]
I believe this is done. Could you please close the issue.
