### ISSUE TITLE
Improve the dockerfile for mongo-client image

### ISSUE THREAD

**Issue by ksatchit** [openebs/test-tools#41]
## Is this a BUG REPORT or FEATURE REQUEST?
 FEATURE REQUEST

**What happened**:

- Update the mongo-client dockerfile as per standard best practice - https://github.com/openebs/test-tools/tree/master/mongo-client

**What you expected to happen**:

- Optimized images

**Anything else we need to know?**:

- Refer https://docs.docker.com/develop/develop-images/dockerfile_best-practices/

**Comment by bilal-mk** [comment]
I would like to contribute this
