### ISSUE TITLE
Improve the dockerfile for postgres-client image

### ISSUE THREAD

**Issue by ksatchit** [openebs/test-tools#43]
## Is this a BUG REPORT or FEATURE REQUEST?
FEATURE REQUEST

**What happened**:

- Update the mongo-client dockerfile as per standard best practice - https://github.com/openebs/test-tools/tree/master/postgres-client

**What you expected to happen**:

- Optimized images

**How to reproduce it (as minimally and precisely as possible)**:

- Refer:  https://docs.docker.com/develop/develop-images/dockerfile_best-practices/

**Anything else we need to know?**:

**Comment by MrL1605** [comment]
Can someone assign this issue to me. I'll work on similar issues

**Comment by Sagar2366** [comment]
is this issue still open ?

**Comment by MrL1605** [comment]
It can be closed now as optimizations have been merged.

**Comment by ksatchit** [comment]
Closed on account of #44
