### ISSUE TITLE
Add comments in the code and fix linting issue

### ISSUE THREAD

**Issue by Akash4927** [openebs/test-tools#52]
##  FEATURE REQUEST?
 

**What happened**:

-  Add Comments in the code and fix linting issue

https://github.com/openebs/test-tools/blob/master/custom-client/liveness.py

**Comment by Abhishekguragol** [comment]
I'll work on this

**Comment by Abhishekguragol** [comment]
Do you have any list of the issues you are facing

**Comment by toozdey** [comment]
Completed: https://github.com/openebs/test-tools/pull/59
